# Generated by Django 5.2 on 2025-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('skills', models.TextField()),
                ('photo', models.ImageField(upload_to='about_me_photos/')),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
